kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: harbor.home.hoffmeister.biz/diztortion/exim4
      registry: harbor.home.hoffmeister.biz
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
